# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handyplug.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='handyplug.proto',
  package='handyplug',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fhandyplug.proto\x12\thandyplug\"\x10\n\x02Ok\x12\n\n\x02Id\x18\x01 \x01(\r\"<\n\x05\x45rror\x12\n\n\x02Id\x18\x01 \x01(\r\x12\x14\n\x0c\x45rrorMessage\x18\x02 \x01(\t\x12\x11\n\tErrorCode\x18\x03 \x01(\x05\"\x12\n\x04Ping\x12\n\n\x02Id\x18\x01 \x01(\r\"K\n\x11RequestServerInfo\x12\n\n\x02Id\x18\x01 \x01(\r\x12\x12\n\nClientName\x18\x02 \x01(\t\x12\x16\n\x0eMessageVersion\x18\x03 \x01(\r\"Y\n\nServerInfo\x12\n\n\x02Id\x18\x01 \x01(\r\x12\x12\n\nServerName\x18\x02 \x01(\t\x12\x16\n\x0eMessageVersion\x18\x03 \x01(\r\x12\x13\n\x0bMaxPingTime\x18\x04 \x01(\r\"\x97\x01\n\tLinearCmd\x12\n\n\x02Id\x18\x01 \x01(\r\x12\x13\n\x0b\x44\x65viceIndex\x18\x02 \x01(\r\x12,\n\x07Vectors\x18\x03 \x03(\x0b\x32\x1b.handyplug.LinearCmd.Vector\x1a;\n\x06Vector\x12\r\n\x05Index\x18\x01 \x01(\r\x12\x10\n\x08\x44uration\x18\x02 \x01(\r\x12\x10\n\x08Position\x18\x03 \x01(\x01\"\x8b\x02\n\x07Message\x12\x1b\n\x02Ok\x18\x64 \x01(\x0b\x32\r.handyplug.OkH\x00\x12!\n\x05\x45rror\x18\x65 \x01(\x0b\x32\x10.handyplug.ErrorH\x00\x12\x1f\n\x04Ping\x18\x66 \x01(\x0b\x32\x0f.handyplug.PingH\x00\x12:\n\x11RequestServerInfo\x18\xc8\x01 \x01(\x0b\x32\x1c.handyplug.RequestServerInfoH\x00\x12,\n\nServerInfo\x18\xc9\x01 \x01(\x0b\x32\x15.handyplug.ServerInfoH\x00\x12*\n\tLinearCmd\x18\x93\x03 \x01(\x0b\x32\x14.handyplug.LinearCmdH\x00\x42\t\n\x07Message\"/\n\x07Payload\x12$\n\x08Messages\x18\x01 \x03(\x0b\x32\x12.handyplug.Messageb\x06proto3'
)




_OK = _descriptor.Descriptor(
  name='Ok',
  full_name='handyplug.Ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.Ok.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=46,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='handyplug.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.Error.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorMessage', full_name='handyplug.Error.ErrorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorCode', full_name='handyplug.Error.ErrorCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=108,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='handyplug.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.Ping.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=128,
)


_REQUESTSERVERINFO = _descriptor.Descriptor(
  name='RequestServerInfo',
  full_name='handyplug.RequestServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.RequestServerInfo.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClientName', full_name='handyplug.RequestServerInfo.ClientName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MessageVersion', full_name='handyplug.RequestServerInfo.MessageVersion', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=205,
)


_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='handyplug.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.ServerInfo.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ServerName', full_name='handyplug.ServerInfo.ServerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MessageVersion', full_name='handyplug.ServerInfo.MessageVersion', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaxPingTime', full_name='handyplug.ServerInfo.MaxPingTime', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=296,
)


_LINEARCMD_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='handyplug.LinearCmd.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Index', full_name='handyplug.LinearCmd.Vector.Index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='handyplug.LinearCmd.Vector.Duration', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Position', full_name='handyplug.LinearCmd.Vector.Position', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=450,
)

_LINEARCMD = _descriptor.Descriptor(
  name='LinearCmd',
  full_name='handyplug.LinearCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='handyplug.LinearCmd.Id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DeviceIndex', full_name='handyplug.LinearCmd.DeviceIndex', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Vectors', full_name='handyplug.LinearCmd.Vectors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LINEARCMD_VECTOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=450,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='handyplug.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ok', full_name='handyplug.Message.Ok', index=0,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Error', full_name='handyplug.Message.Error', index=1,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ping', full_name='handyplug.Message.Ping', index=2,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequestServerInfo', full_name='handyplug.Message.RequestServerInfo', index=3,
      number=200, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ServerInfo', full_name='handyplug.Message.ServerInfo', index=4,
      number=201, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LinearCmd', full_name='handyplug.Message.LinearCmd', index=5,
      number=403, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Message', full_name='handyplug.Message.Message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=453,
  serialized_end=720,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='handyplug.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Messages', full_name='handyplug.Payload.Messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=769,
)

_LINEARCMD_VECTOR.containing_type = _LINEARCMD
_LINEARCMD.fields_by_name['Vectors'].message_type = _LINEARCMD_VECTOR
_MESSAGE.fields_by_name['Ok'].message_type = _OK
_MESSAGE.fields_by_name['Error'].message_type = _ERROR
_MESSAGE.fields_by_name['Ping'].message_type = _PING
_MESSAGE.fields_by_name['RequestServerInfo'].message_type = _REQUESTSERVERINFO
_MESSAGE.fields_by_name['ServerInfo'].message_type = _SERVERINFO
_MESSAGE.fields_by_name['LinearCmd'].message_type = _LINEARCMD
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['Ok'])
_MESSAGE.fields_by_name['Ok'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['Error'])
_MESSAGE.fields_by_name['Error'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['Ping'])
_MESSAGE.fields_by_name['Ping'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['RequestServerInfo'])
_MESSAGE.fields_by_name['RequestServerInfo'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['ServerInfo'])
_MESSAGE.fields_by_name['ServerInfo'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_MESSAGE.oneofs_by_name['Message'].fields.append(
  _MESSAGE.fields_by_name['LinearCmd'])
_MESSAGE.fields_by_name['LinearCmd'].containing_oneof = _MESSAGE.oneofs_by_name['Message']
_PAYLOAD.fields_by_name['Messages'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Ok'] = _OK
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['RequestServerInfo'] = _REQUESTSERVERINFO
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['LinearCmd'] = _LINEARCMD
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ok = _reflection.GeneratedProtocolMessageType('Ok', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.Ok)
  })
_sym_db.RegisterMessage(Ok)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.Error)
  })
_sym_db.RegisterMessage(Error)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.Ping)
  })
_sym_db.RegisterMessage(Ping)

RequestServerInfo = _reflection.GeneratedProtocolMessageType('RequestServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSERVERINFO,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.RequestServerInfo)
  })
_sym_db.RegisterMessage(RequestServerInfo)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.ServerInfo)
  })
_sym_db.RegisterMessage(ServerInfo)

LinearCmd = _reflection.GeneratedProtocolMessageType('LinearCmd', (_message.Message,), {

  'Vector' : _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
    'DESCRIPTOR' : _LINEARCMD_VECTOR,
    '__module__' : 'handyplug_pb2'
    # @@protoc_insertion_point(class_scope:handyplug.LinearCmd.Vector)
    })
  ,
  'DESCRIPTOR' : _LINEARCMD,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.LinearCmd)
  })
_sym_db.RegisterMessage(LinearCmd)
_sym_db.RegisterMessage(LinearCmd.Vector)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.Message)
  })
_sym_db.RegisterMessage(Message)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'handyplug_pb2'
  # @@protoc_insertion_point(class_scope:handyplug.Payload)
  })
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
